// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvprtzaatfbvdxwutrbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12cHJ0emFhdGZidmR4d3V0cmJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk5MDAxMzYsImV4cCI6MjA4NTQ3NjEzNn0.eep2bffMSjclffZFmhm6ZFffeSD_gu3T9k2v3vcPTcE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});